#' Import table of bp covered by target
#'
#' @param targetbp path to folder generated by PrepareTargetPositions.R
#' @return

chromosomes = read.delim(file = file.path(targetbp,"bpcovered.tsv"),as.is=T)
chromosomes = sort(paste0("chr",chromosomes[-nrow(chromosomes),1]))

# Import table of bp covered by target
totpos = read.delim(file=file.path(targetbp,"bpcovered.tsv"),header = T,as.is=T,sep = "\t")
rownames(totpos) = paste0("chr",totpos$chromosome)
totpos = totpos[chromosomes,]
totpos$bp_covered_fraction = totpos$bp_covered/sum(totpos$bp_covered)
