#' Import and process data necessary for abemus workflow.
#' @param samples.info.file A tab-delimited two columns file listing case and control samples.
#' @param pacbam Path to folder with data generated by PaCBAM.
#' @return A list with following objects:
#' @export
importData <- function(samples.info.file,pacbam){

  chroms <- c(1:22,'X','Y')

  sif <- read.sif(samples.info.file)

  ref <- lapply(chroms,getLoci,pacbam,select = 'ref')
  pos <- lapply(chroms,getLoci,pacbam,select = 'pos')
  rsid<- lapply(chroms,getLoci,pacbam,select = 'rsid') %>% lapply(function(x) which(!is.na(x)))

  mat_vaf <- lapply(chroms,pileup2mat,sif,pacbam,select='af',sparse=FALSE)
  mat_cov <- lapply(chroms,pileup2mat,sif,pacbam,select='cov',sparse=FALSE)

  mat_cov_base <- list()
  for(base in c('A','C','G','T')){
    mat_cov_base[[base]] <- lapply(c(1:22,'X','Y'),pileup2mat,sif,pacbam,select=base,sparse=FALSE)
  }

  return(list(sif=sif,
              ref=ref,
              pos=pos,
              rsid=rsid,
              mat_vaf=mat_vaf,
              mat_cov=mat_cov,
              mat_cov_base=mat_cov_base))

}
