#' Split PaCBAM ouputs by chromosomes
#' @param targetbed Target regions in BED format
#' @param pacbamfolder Folder with original outputs generated by PaCBAM. This folder should contain both .pabs and .pileups files.
#' @param mc.cores Process n chromosomes in parallel. default = 1
#' @param pacbamfolder_bychrom Output folder in which subfolders for each sample will be created.
#' @export
split_pacbam_bychrom <- function(targetbed,
                                 pacbamfolder,
                                 mc.cores=1,
                                 pacbamfolder_bychrom){

  pacbamlist = list.files(pacbamfolder,full.names = TRUE, pattern = "\\.pabs$|\\.pileup$")
  samplelist = unique(gsub(basename(pacbamlist),pattern = '.pabs|.pileup',replacement = ''))

  message(paste("[",Sys.time(),"]\tReading chromosomes from 'targetbed'","\n"))
  CHR <- bed2positions(targetbed = targetbed,get_only_chromosomes = TRUE)[[1]]

  for(sname in samplelist){
    dirname <- sname
    message(paste("[",Sys.time(),"]\t",dirname,"\twrite pileup_bychrom...\t"))
    dir.create(file.path(pacbamfolder_bychrom,dirname))
    dir.create(file.path(pacbamfolder_bychrom,dirname,"pileup"))
    setwd(file.path(pacbamfolder_bychrom,dirname,"pileup"))
    pileup_list = grep(pacbamlist,pattern = "\\.pileup$",value = TRUE)
    pileup_file = grep(pileup_list,pattern = paste(dirname,"pileup",sep="."),value = TRUE)
    mclapply(seq(1,length(CHR),1),pileup_splitbychr,CHR=CHR,pileup_file=pileup_file,mc.cores=mc.cores)
    message("done.\n")
    message(paste("[",Sys.time(),"]\t",dirname,"\twrite pabs_bychrom...\t"))
    dir.create(file.path(pacbamfolder_bychrom,dirname,"snvs"))
    setwd(file.path(pacbamfolder_bychrom,dirname,"snvs"))
    pabs_list = grep(pacbamlist,pattern = "\\.pabs$",value = TRUE)
    pabs_file = grep(pabs_list,pattern = paste(dirname,"pabs",sep="."),value = TRUE)
    mclapply(seq(1,length(CHR),1),pabs_splitbychr,CHR=CHR,snvs_file=pabs_file,mc.cores=mc.cores)
    message("done.\n")
  }

}
